### PR TITLE
Add Python 3.4 support

### PR DESCRIPTION
**Pull request by eeue56**

### CODE REVIEW

**Comment by eeue56** [comment]
I'll update this branch as I hit more issues.

**Comment by ralhei** [comment]
Hi eeue56,
thanks for your contribution. 
Should I wait for more updates from you, or merge it now?
I've just rerun my unittests under Python3.4 and the problem you found was also the only one that popped up in my tests.

**Comment by ralhei** [comment]
OK, I've decided to merge now and submit a few other patches from my side. Thanks anyway!!

**Comment by eeue56** [comment]
Seems to be working for me fine, no further errors

**Pull request merged**
